version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: intern_assignment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=intern_assignment_db
      - JWT_SECRET=dev_secret_change
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db-data:
